export const characters = [
	{
		id: 1011334,
		name: '3-D Man',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/c/e0/535fecbbb9784.jpg',
		favorite: true,
	},
	{
		id: 1017100,
		name: 'A-Bomb (HAS)',
		description:
			"Rick Jones has been Hulk's best bud since day one, but now he's more than a friend...he's a teammate! Transformed by a Gamma energy explosion, A-Bomb's thick, armored skin is just as strong and powerful as it is blue. And when he curls into action, he uses it like a giant bowling ball of destruction! ",
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/3/20/5232158de5b16.jpg',
		favorite: false,
	},
	{
		id: 1009144,
		name: 'A.I.M.',
		description: 'AIM is a terrorist organization bent on destroying the world.',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/6/20/52602f21f29ec.jpg',
		favorite: false,
	},
	{
		id: 1010699,
		name: 'Aaron Stack',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1009146,
		name: 'Abomination (Emil Blonsky)',
		description:
			'Formerly known as Emil Blonsky, a spy of Soviet Yugoslavian origin working for the KGB, the Abomination gained his powers after receiving a dose of gamma radiation similar to that which transformed Bruce Banner into the incredible Hulk.',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/9/50/4ce18691cbf04.jpg',
		favorite: false,
	},
	{
		id: 1016823,
		name: 'Abomination (Ultimate)',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1009148,
		name: 'Absorbing Man',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/1/b0/5269678709fb7.jpg',
		favorite: false,
	},
	{
		id: 1009149,
		name: 'Abyss',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/9/30/535feab462a64.jpg',
		favorite: false,
	},
	{
		id: 1010903,
		name: 'Abyss (Age of Apocalypse)',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/3/80/4c00358ec7548.jpg',
		favorite: false,
	},
	{
		id: 1011266,
		name: 'Adam Destine',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1010354,
		name: 'Adam Warlock',
		description:
			'Adam Warlock is an artificially created human who was born in a cocoon at a scientific complex called The Beehive.',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/a/f0/5202887448860.jpg',
		favorite: false,
	},
	{
		id: 1010846,
		name: 'Aegis (Trey Rollins)',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/5/e0/4c0035c9c425d.gif',
		favorite: false,
	},
	{
		id: 1017851,
		name: 'Aero (Aero)',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1012717,
		name: 'Agatha Harkness',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/c/a0/4ce5a9bf70e19.jpg',
		favorite: false,
	},
	{
		id: 1011297,
		name: 'Agent Brand',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/4/60/52695285d6e7e.jpg',
		favorite: false,
	},
	{
		id: 1011031,
		name: 'Agent X (Nijo)',
		description:
			"Originally a partner of the mind-altering assassin Black Swan, Nijo spied on Deadpool as part of the Swan's plan to exact revenge for Deadpool falsely taking credit for the Swan's assassination of the Four Winds crime family, which included Nijo's brother.",
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1009150,
		name: 'Agent Zero',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/f/60/4c0042121d790.jpg',
		favorite: false,
	},
	{
		id: 1011198,
		name: 'Agents of Atlas',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/9/a0/4ce18a834b7f5.jpg',
		favorite: false,
	},
	{
		id: 1011175,
		name: 'Aginar',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1011136,
		name: 'Air-Walker (Gabriel Lan)',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1011176,
		name: 'Ajak',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/2/80/4c002f35c5215.jpg',
		favorite: false,
	},
	{
		id: 1010870,
		name: 'Ajaxis',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/70/4c0035adc7d3a.jpg',
		favorite: false,
	},
	{
		id: 1011194,
		name: 'Akemi',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1011170,
		name: 'Alain',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1009240,
		name: 'Albert Cleary',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1011120,
		name: 'Albion',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1010836,
		name: 'Alex Power',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/9/50/4ce5a385a2e82.jpg',
		favorite: false,
	},
	{
		id: 1010755,
		name: 'Alex Wilder',
		description:
			'Despite being the only one of the Runaways without any superhuman abilities or tech, Alex Wilder became the de facto leader of the group due to his natural leadership skills and intellect, as well as prodigy-level logic and strategy.',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/2/c0/4c00377144d5a.jpg',
		favorite: false,
	},
	{
		id: 1011214,
		name: 'Alexa Mendez',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1009497,
		name: 'Alexander Pierce',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1014990,
		name: 'Alice',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/6/70/4cd061e6d6573.jpg',
		favorite: false,
	},
	{
		id: 1009435,
		name: 'Alicia Masters',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/4c003d40ac7ae.jpg',
		favorite: false,
	},
	{
		id: 1010370,
		name: 'Alpha Flight',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/1/60/52695277ee088.jpg',
		favorite: false,
	},
	{
		id: 1011324,
		name: 'Alpha Flight (Ultimate)',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1011164,
		name: 'Alvin Maker',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1011227,
		name: 'Amadeus Cho',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/3/80/520288b9cb581.jpg',
		favorite: false,
	},
	{
		id: 1009567,
		name: 'Amanda Sefton',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1011382,
		name: 'Amazoness',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1011361,
		name: 'American Eagle (Jason Strongbow)',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/f/80/4ce5a6d8b8f2a.jpg',
		favorite: false,
	},
	{
		id: 1009151,
		name: 'Amiko',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1010672,
		name: 'Amora',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1010673,
		name: 'Amphibian (Earth-712)',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1010905,
		name: 'Amun',
		description:
			"Amun is a ruthless teenage assassin, employed by the Sisterhood of the Wasp to serve under the mage Vincent after Araña interrupted the ritual to initiate the Wasp's new chosen one.",
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1009152,
		name: 'Ancient One',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/b0/4ce59ea2103ac.jpg',
		favorite: false,
	},
	{
		id: 1016824,
		name: 'Ancient One (Ultimate)',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1011684,
		name: 'Angel (Angel Salvadore)',
		description:
			'Driven out of home by her abusive step-father, fourteen-year old Angel Salvadore slept in the woods, where her mutant nature manifested itself in the form of a protective cocoon.',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1011396,
		name: 'Angel (Thomas Halloway)',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/d/03/531769834b15f.jpg',
		favorite: false,
	},
	{
		id: 1011338,
		name: 'Angel (Ultimate)',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/4/50/531769ae4399f.jpg',
		favorite: false,
	},
	{
		id: 1009153,
		name: 'Angel (Warren Worthington III)',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available.jpg',
		favorite: false,
	},
	{
		id: 1017574,
		name: 'Angela (Aldrif Odinsdottir)',
		description: '',
		image: 'http://i.annihil.us/u/prod/marvel/i/mg/7/00/545a82f59dd73.jpg',
		favorite: false,
	},
];
